-- AlterTable
ALTER TABLE "Posts" ALTER COLUMN "createdAt" DROP DEFAULT,
ALTER COLUMN "createdAt" SET DATA TYPE TEXT,
ALTER COLUMN "editedAt" DROP DEFAULT,
ALTER COLUMN "editedAt" SET DATA TYPE TEXT;
